CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    `password` VARCHAR(255),
    reg_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);